### ISSUE TITLE
回调地址

### ISSUE THREAD

**Issue by 0x7962** [dxjia/DoubanTop#1]
在douban上创建应用的时候需要填写回调地址，但是没有自己的服务器怎么填啊？

**Comment by dxjia** [comment]
@YBJAY00000 如果不会用到它的auth 2.0登录认证api，可以随便写一个就好，这个回调地址是给账号登录授权用的，因为我没用到，所以我随便填的www.baidu.com

**Comment by 0x7962** [comment]
@dxjia 好的，谢啦。
