### ISSUE TITLE
gitignore完善

### ISSUE THREAD

**Issue by msdx** [dxjia/DoubanTop#2]
对于生成的文件，如APK，.iml文件，.idea文件夹，建议不要加入到版本控制当中。
可参考：https://github.com/github/gitignore

**Comment by dxjia** [comment]
@msdx 多谢指出。
稍后会修改一下，不过 .idea整个文件夹都需要排除在外嘛？

**Comment by msdx** [comment]
.idea是可以排除在外的，因为里面的文件都由IDE生成，并且没有它不影响一个项目的导入。在gitignore这个项目中也是这样做的。

**Comment by msdx** [comment]
apk可以在release之后，作为release附件传到github来提供。

**Comment by dxjia** [comment]
确实利索很多。Thanks。

**Comment by dxjia** [comment]
update gitignore file done.
